import type { Pin } from "./types"

export const mockPins: Pin[] = [
  {
    id: "1",
    title: "Modern Minimalist Interior",
    description: "Clean lines and natural light create a serene living space",
    imageUrl: "/modern-minimalist-interior-design.jpg",
    imageWidth: 400,
    imageHeight: 600,
    userId: "1",
    userName: "Sarah Design",
    userAvatar: "/sarah-avatar.png",
    tags: ["interior", "minimalist", "design"],
    likes: 234,
    comments: 12,
    saves: 89,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "2",
    title: "Sunset Mountain Landscape",
    description: "Golden hour over the peaks",
    imageUrl: "/sunset-mountain-landscape.jpg",
    imageWidth: 400,
    imageHeight: 500,
    userId: "2",
    userName: "Nature Lens",
    userAvatar: "/nature-photographer.jpg",
    tags: ["nature", "landscape", "photography"],
    likes: 567,
    comments: 23,
    saves: 234,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "3",
    title: "Artisan Coffee Setup",
    description: "The perfect morning ritual",
    imageUrl: "/artisan-coffee-setup.jpg",
    imageWidth: 400,
    imageHeight: 550,
    userId: "3",
    userName: "Coffee Culture",
    userAvatar: "/coffee-lover.jpg",
    tags: ["coffee", "lifestyle", "morning"],
    likes: 432,
    comments: 18,
    saves: 156,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: "4",
    title: "Abstract Geometric Art",
    description: "Bold shapes and vibrant colors",
    imageUrl: "/abstract-geometric-art.png",
    imageWidth: 400,
    imageHeight: 700,
    userId: "4",
    userName: "Art Studio",
    userAvatar: "/artist-avatar.png",
    tags: ["art", "abstract", "geometric"],
    likes: 789,
    comments: 34,
    saves: 345,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: "5",
    title: "Cozy Reading Nook",
    description: "The perfect spot to escape with a good book",
    imageUrl: "/cozy-reading-nook.jpg",
    imageWidth: 400,
    imageHeight: 650,
    userId: "1",
    userName: "Sarah Design",
    userAvatar: "/sarah-avatar.png",
    tags: ["interior", "cozy", "books"],
    likes: 345,
    comments: 15,
    saves: 123,
    createdAt: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: "6",
    title: "Fresh Pasta Making",
    description: "Homemade pasta from scratch",
    imageUrl: "/fresh-pasta-making.jpg",
    imageWidth: 400,
    imageHeight: 500,
    userId: "5",
    userName: "Chef's Table",
    userAvatar: "/chef-avatar.png",
    tags: ["food", "cooking", "pasta"],
    likes: 678,
    comments: 45,
    saves: 289,
    createdAt: new Date(Date.now() - 518400000).toISOString(),
  },
]
